/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppVentasRouteImport } from './routes/app.ventas'
import { Route as AppSuppliersRouteImport } from './routes/app.suppliers'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppSalidasRouteImport } from './routes/app.salidas'
import { Route as AppSalaEsperaRouteImport } from './routes/app.sala-espera'
import { Route as AppPurchaseOrdersRouteImport } from './routes/app.purchase-orders'
import { Route as AppPacientesRouteImport } from './routes/app.pacientes'
import { Route as AppNominaRouteImport } from './routes/app.nomina'
import { Route as AppMovementsRouteImport } from './routes/app.movements'
import { Route as AppLocationsRouteImport } from './routes/app.locations'
import { Route as AppHospitalizacionRouteImport } from './routes/app.hospitalizacion'
import { Route as AppHelpRouteImport } from './routes/app.help'
import { Route as AppFinanzasRouteImport } from './routes/app.finanzas'
import { Route as AppEmpleadosRouteImport } from './routes/app.empleados'
import { Route as AppDashboardRouteImport } from './routes/app.dashboard'
import { Route as AppCuentasRouteImport } from './routes/app.cuentas'
import { Route as AppConsultasRouteImport } from './routes/app.consultas'
import { Route as AppComisionesRouteImport } from './routes/app.comisiones'
import { Route as AppChecadorRouteImport } from './routes/app.checador'
import { Route as AppCatalogRouteImport } from './routes/app.catalog'
import { Route as AppAnalyticsRouteImport } from './routes/app.analytics'
import { Route as AppAgendaRouteImport } from './routes/app.agenda'
import { Route as AppActivosRouteImport } from './routes/app.activos'
import { Route as AppPacientesIndexRouteImport } from './routes/app.pacientes.index'
import { Route as AppPacientesIdRouteImport } from './routes/app.pacientes.$id'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppVentasRoute = AppVentasRouteImport.update({
  id: '/ventas',
  path: '/ventas',
  getParentRoute: () => AppRoute,
} as any)
const AppSuppliersRoute = AppSuppliersRouteImport.update({
  id: '/suppliers',
  path: '/suppliers',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppSalidasRoute = AppSalidasRouteImport.update({
  id: '/salidas',
  path: '/salidas',
  getParentRoute: () => AppRoute,
} as any)
const AppSalaEsperaRoute = AppSalaEsperaRouteImport.update({
  id: '/sala-espera',
  path: '/sala-espera',
  getParentRoute: () => AppRoute,
} as any)
const AppPurchaseOrdersRoute = AppPurchaseOrdersRouteImport.update({
  id: '/purchase-orders',
  path: '/purchase-orders',
  getParentRoute: () => AppRoute,
} as any)
const AppPacientesRoute = AppPacientesRouteImport.update({
  id: '/pacientes',
  path: '/pacientes',
  getParentRoute: () => AppRoute,
} as any)
const AppNominaRoute = AppNominaRouteImport.update({
  id: '/nomina',
  path: '/nomina',
  getParentRoute: () => AppRoute,
} as any)
const AppMovementsRoute = AppMovementsRouteImport.update({
  id: '/movements',
  path: '/movements',
  getParentRoute: () => AppRoute,
} as any)
const AppLocationsRoute = AppLocationsRouteImport.update({
  id: '/locations',
  path: '/locations',
  getParentRoute: () => AppRoute,
} as any)
const AppHospitalizacionRoute = AppHospitalizacionRouteImport.update({
  id: '/hospitalizacion',
  path: '/hospitalizacion',
  getParentRoute: () => AppRoute,
} as any)
const AppHelpRoute = AppHelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => AppRoute,
} as any)
const AppFinanzasRoute = AppFinanzasRouteImport.update({
  id: '/finanzas',
  path: '/finanzas',
  getParentRoute: () => AppRoute,
} as any)
const AppEmpleadosRoute = AppEmpleadosRouteImport.update({
  id: '/empleados',
  path: '/empleados',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppCuentasRoute = AppCuentasRouteImport.update({
  id: '/cuentas',
  path: '/cuentas',
  getParentRoute: () => AppRoute,
} as any)
const AppConsultasRoute = AppConsultasRouteImport.update({
  id: '/consultas',
  path: '/consultas',
  getParentRoute: () => AppRoute,
} as any)
const AppComisionesRoute = AppComisionesRouteImport.update({
  id: '/comisiones',
  path: '/comisiones',
  getParentRoute: () => AppRoute,
} as any)
const AppChecadorRoute = AppChecadorRouteImport.update({
  id: '/checador',
  path: '/checador',
  getParentRoute: () => AppRoute,
} as any)
const AppCatalogRoute = AppCatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => AppRoute,
} as any)
const AppAnalyticsRoute = AppAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AppRoute,
} as any)
const AppAgendaRoute = AppAgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => AppRoute,
} as any)
const AppActivosRoute = AppActivosRouteImport.update({
  id: '/activos',
  path: '/activos',
  getParentRoute: () => AppRoute,
} as any)
const AppPacientesIndexRoute = AppPacientesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppPacientesRoute,
} as any)
const AppPacientesIdRoute = AppPacientesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppPacientesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/app/activos': typeof AppActivosRoute
  '/app/agenda': typeof AppAgendaRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/catalog': typeof AppCatalogRoute
  '/app/checador': typeof AppChecadorRoute
  '/app/comisiones': typeof AppComisionesRoute
  '/app/consultas': typeof AppConsultasRoute
  '/app/cuentas': typeof AppCuentasRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/empleados': typeof AppEmpleadosRoute
  '/app/finanzas': typeof AppFinanzasRoute
  '/app/help': typeof AppHelpRoute
  '/app/hospitalizacion': typeof AppHospitalizacionRoute
  '/app/locations': typeof AppLocationsRoute
  '/app/movements': typeof AppMovementsRoute
  '/app/nomina': typeof AppNominaRoute
  '/app/pacientes': typeof AppPacientesRouteWithChildren
  '/app/purchase-orders': typeof AppPurchaseOrdersRoute
  '/app/sala-espera': typeof AppSalaEsperaRoute
  '/app/salidas': typeof AppSalidasRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/suppliers': typeof AppSuppliersRoute
  '/app/ventas': typeof AppVentasRoute
  '/app/': typeof AppIndexRoute
  '/app/pacientes/$id': typeof AppPacientesIdRoute
  '/app/pacientes/': typeof AppPacientesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/app/activos': typeof AppActivosRoute
  '/app/agenda': typeof AppAgendaRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/catalog': typeof AppCatalogRoute
  '/app/checador': typeof AppChecadorRoute
  '/app/comisiones': typeof AppComisionesRoute
  '/app/consultas': typeof AppConsultasRoute
  '/app/cuentas': typeof AppCuentasRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/empleados': typeof AppEmpleadosRoute
  '/app/finanzas': typeof AppFinanzasRoute
  '/app/help': typeof AppHelpRoute
  '/app/hospitalizacion': typeof AppHospitalizacionRoute
  '/app/locations': typeof AppLocationsRoute
  '/app/movements': typeof AppMovementsRoute
  '/app/nomina': typeof AppNominaRoute
  '/app/purchase-orders': typeof AppPurchaseOrdersRoute
  '/app/sala-espera': typeof AppSalaEsperaRoute
  '/app/salidas': typeof AppSalidasRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/suppliers': typeof AppSuppliersRoute
  '/app/ventas': typeof AppVentasRoute
  '/app': typeof AppIndexRoute
  '/app/pacientes/$id': typeof AppPacientesIdRoute
  '/app/pacientes': typeof AppPacientesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/app/activos': typeof AppActivosRoute
  '/app/agenda': typeof AppAgendaRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/catalog': typeof AppCatalogRoute
  '/app/checador': typeof AppChecadorRoute
  '/app/comisiones': typeof AppComisionesRoute
  '/app/consultas': typeof AppConsultasRoute
  '/app/cuentas': typeof AppCuentasRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/empleados': typeof AppEmpleadosRoute
  '/app/finanzas': typeof AppFinanzasRoute
  '/app/help': typeof AppHelpRoute
  '/app/hospitalizacion': typeof AppHospitalizacionRoute
  '/app/locations': typeof AppLocationsRoute
  '/app/movements': typeof AppMovementsRoute
  '/app/nomina': typeof AppNominaRoute
  '/app/pacientes': typeof AppPacientesRouteWithChildren
  '/app/purchase-orders': typeof AppPurchaseOrdersRoute
  '/app/sala-espera': typeof AppSalaEsperaRoute
  '/app/salidas': typeof AppSalidasRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/suppliers': typeof AppSuppliersRoute
  '/app/ventas': typeof AppVentasRoute
  '/app/': typeof AppIndexRoute
  '/app/pacientes/$id': typeof AppPacientesIdRoute
  '/app/pacientes/': typeof AppPacientesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/login'
    | '/app/activos'
    | '/app/agenda'
    | '/app/analytics'
    | '/app/catalog'
    | '/app/checador'
    | '/app/comisiones'
    | '/app/consultas'
    | '/app/cuentas'
    | '/app/dashboard'
    | '/app/empleados'
    | '/app/finanzas'
    | '/app/help'
    | '/app/hospitalizacion'
    | '/app/locations'
    | '/app/movements'
    | '/app/nomina'
    | '/app/pacientes'
    | '/app/purchase-orders'
    | '/app/sala-espera'
    | '/app/salidas'
    | '/app/settings'
    | '/app/suppliers'
    | '/app/ventas'
    | '/app/'
    | '/app/pacientes/$id'
    | '/app/pacientes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/app/activos'
    | '/app/agenda'
    | '/app/analytics'
    | '/app/catalog'
    | '/app/checador'
    | '/app/comisiones'
    | '/app/consultas'
    | '/app/cuentas'
    | '/app/dashboard'
    | '/app/empleados'
    | '/app/finanzas'
    | '/app/help'
    | '/app/hospitalizacion'
    | '/app/locations'
    | '/app/movements'
    | '/app/nomina'
    | '/app/purchase-orders'
    | '/app/sala-espera'
    | '/app/salidas'
    | '/app/settings'
    | '/app/suppliers'
    | '/app/ventas'
    | '/app'
    | '/app/pacientes/$id'
    | '/app/pacientes'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/login'
    | '/app/activos'
    | '/app/agenda'
    | '/app/analytics'
    | '/app/catalog'
    | '/app/checador'
    | '/app/comisiones'
    | '/app/consultas'
    | '/app/cuentas'
    | '/app/dashboard'
    | '/app/empleados'
    | '/app/finanzas'
    | '/app/help'
    | '/app/hospitalizacion'
    | '/app/locations'
    | '/app/movements'
    | '/app/nomina'
    | '/app/pacientes'
    | '/app/purchase-orders'
    | '/app/sala-espera'
    | '/app/salidas'
    | '/app/settings'
    | '/app/suppliers'
    | '/app/ventas'
    | '/app/'
    | '/app/pacientes/$id'
    | '/app/pacientes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/ventas': {
      id: '/app/ventas'
      path: '/ventas'
      fullPath: '/app/ventas'
      preLoaderRoute: typeof AppVentasRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/suppliers': {
      id: '/app/suppliers'
      path: '/suppliers'
      fullPath: '/app/suppliers'
      preLoaderRoute: typeof AppSuppliersRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/salidas': {
      id: '/app/salidas'
      path: '/salidas'
      fullPath: '/app/salidas'
      preLoaderRoute: typeof AppSalidasRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/sala-espera': {
      id: '/app/sala-espera'
      path: '/sala-espera'
      fullPath: '/app/sala-espera'
      preLoaderRoute: typeof AppSalaEsperaRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/purchase-orders': {
      id: '/app/purchase-orders'
      path: '/purchase-orders'
      fullPath: '/app/purchase-orders'
      preLoaderRoute: typeof AppPurchaseOrdersRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/pacientes': {
      id: '/app/pacientes'
      path: '/pacientes'
      fullPath: '/app/pacientes'
      preLoaderRoute: typeof AppPacientesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/nomina': {
      id: '/app/nomina'
      path: '/nomina'
      fullPath: '/app/nomina'
      preLoaderRoute: typeof AppNominaRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/movements': {
      id: '/app/movements'
      path: '/movements'
      fullPath: '/app/movements'
      preLoaderRoute: typeof AppMovementsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/locations': {
      id: '/app/locations'
      path: '/locations'
      fullPath: '/app/locations'
      preLoaderRoute: typeof AppLocationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/hospitalizacion': {
      id: '/app/hospitalizacion'
      path: '/hospitalizacion'
      fullPath: '/app/hospitalizacion'
      preLoaderRoute: typeof AppHospitalizacionRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/help': {
      id: '/app/help'
      path: '/help'
      fullPath: '/app/help'
      preLoaderRoute: typeof AppHelpRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/finanzas': {
      id: '/app/finanzas'
      path: '/finanzas'
      fullPath: '/app/finanzas'
      preLoaderRoute: typeof AppFinanzasRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/empleados': {
      id: '/app/empleados'
      path: '/empleados'
      fullPath: '/app/empleados'
      preLoaderRoute: typeof AppEmpleadosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/dashboard': {
      id: '/app/dashboard'
      path: '/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/cuentas': {
      id: '/app/cuentas'
      path: '/cuentas'
      fullPath: '/app/cuentas'
      preLoaderRoute: typeof AppCuentasRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/consultas': {
      id: '/app/consultas'
      path: '/consultas'
      fullPath: '/app/consultas'
      preLoaderRoute: typeof AppConsultasRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/comisiones': {
      id: '/app/comisiones'
      path: '/comisiones'
      fullPath: '/app/comisiones'
      preLoaderRoute: typeof AppComisionesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/checador': {
      id: '/app/checador'
      path: '/checador'
      fullPath: '/app/checador'
      preLoaderRoute: typeof AppChecadorRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/catalog': {
      id: '/app/catalog'
      path: '/catalog'
      fullPath: '/app/catalog'
      preLoaderRoute: typeof AppCatalogRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/analytics': {
      id: '/app/analytics'
      path: '/analytics'
      fullPath: '/app/analytics'
      preLoaderRoute: typeof AppAnalyticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/agenda': {
      id: '/app/agenda'
      path: '/agenda'
      fullPath: '/app/agenda'
      preLoaderRoute: typeof AppAgendaRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/activos': {
      id: '/app/activos'
      path: '/activos'
      fullPath: '/app/activos'
      preLoaderRoute: typeof AppActivosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/pacientes/': {
      id: '/app/pacientes/'
      path: '/'
      fullPath: '/app/pacientes/'
      preLoaderRoute: typeof AppPacientesIndexRouteImport
      parentRoute: typeof AppPacientesRoute
    }
    '/app/pacientes/$id': {
      id: '/app/pacientes/$id'
      path: '/$id'
      fullPath: '/app/pacientes/$id'
      preLoaderRoute: typeof AppPacientesIdRouteImport
      parentRoute: typeof AppPacientesRoute
    }
  }
}

interface AppPacientesRouteChildren {
  AppPacientesIdRoute: typeof AppPacientesIdRoute
  AppPacientesIndexRoute: typeof AppPacientesIndexRoute
}

const AppPacientesRouteChildren: AppPacientesRouteChildren = {
  AppPacientesIdRoute: AppPacientesIdRoute,
  AppPacientesIndexRoute: AppPacientesIndexRoute,
}

const AppPacientesRouteWithChildren = AppPacientesRoute._addFileChildren(
  AppPacientesRouteChildren,
)

interface AppRouteChildren {
  AppActivosRoute: typeof AppActivosRoute
  AppAgendaRoute: typeof AppAgendaRoute
  AppAnalyticsRoute: typeof AppAnalyticsRoute
  AppCatalogRoute: typeof AppCatalogRoute
  AppChecadorRoute: typeof AppChecadorRoute
  AppComisionesRoute: typeof AppComisionesRoute
  AppConsultasRoute: typeof AppConsultasRoute
  AppCuentasRoute: typeof AppCuentasRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppEmpleadosRoute: typeof AppEmpleadosRoute
  AppFinanzasRoute: typeof AppFinanzasRoute
  AppHelpRoute: typeof AppHelpRoute
  AppHospitalizacionRoute: typeof AppHospitalizacionRoute
  AppLocationsRoute: typeof AppLocationsRoute
  AppMovementsRoute: typeof AppMovementsRoute
  AppNominaRoute: typeof AppNominaRoute
  AppPacientesRoute: typeof AppPacientesRouteWithChildren
  AppPurchaseOrdersRoute: typeof AppPurchaseOrdersRoute
  AppSalaEsperaRoute: typeof AppSalaEsperaRoute
  AppSalidasRoute: typeof AppSalidasRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppSuppliersRoute: typeof AppSuppliersRoute
  AppVentasRoute: typeof AppVentasRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppActivosRoute: AppActivosRoute,
  AppAgendaRoute: AppAgendaRoute,
  AppAnalyticsRoute: AppAnalyticsRoute,
  AppCatalogRoute: AppCatalogRoute,
  AppChecadorRoute: AppChecadorRoute,
  AppComisionesRoute: AppComisionesRoute,
  AppConsultasRoute: AppConsultasRoute,
  AppCuentasRoute: AppCuentasRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppEmpleadosRoute: AppEmpleadosRoute,
  AppFinanzasRoute: AppFinanzasRoute,
  AppHelpRoute: AppHelpRoute,
  AppHospitalizacionRoute: AppHospitalizacionRoute,
  AppLocationsRoute: AppLocationsRoute,
  AppMovementsRoute: AppMovementsRoute,
  AppNominaRoute: AppNominaRoute,
  AppPacientesRoute: AppPacientesRouteWithChildren,
  AppPurchaseOrdersRoute: AppPurchaseOrdersRoute,
  AppSalaEsperaRoute: AppSalaEsperaRoute,
  AppSalidasRoute: AppSalidasRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppSuppliersRoute: AppSuppliersRoute,
  AppVentasRoute: AppVentasRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
